name: PHP Composer

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Verify MySQL connection from container
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Packages
      run: composer install

    - name: Run Init
      run: php init --env=Development

    - name: Build Codecept
      run: composer run-script build-codecept

    - name: Run Codecept
      run: composer run-script run-codecept

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
